baseURL: "https://ananya-kakani-1227.netlify.app"
languageCode: "en-us"
title: "Ananya Kakani"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Ananya Kakani"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/NEUlogo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Ananya Kakani" # Brand name for the brand | default is the title variable
    # disableSearch: false
    # # searchPlaceholder: "Search"
    # menus:
    #   disableAbout: false
    #   disableExperience: false
    #   disableEducation: false
    #   disableProjects: false
    #   disableAchievements: false
    #   disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ananya."
    subtitle: "Cloud Enthusiast"
    content: "A cloud Enthusiast with a focus on AWS, Combining a strong background in Salesforce platform to drive strategic innovations and solutions. Skilled in transforming complex challenges into actionable strategies through the power of cloud technologies."
    image: "/images/me.jpg"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1H-tOKn-ujrSKehhCDu0vVgf7TxZtoWE2/view?usp=drive_link"
      download: true
      newPage: false
    socialNetworks:
      github: https://github.com/AnanyaKakani
      linkedin: https://www.linkedin.com/in/ananya-kakani-0671a71b5/
      

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me1.jpg"
    content: |-
      As a passionate cloud enthusiast with a specialization in AWS, 
      I bring together a solid foundation in cloud computing, 
      gained from my Master of Science in Information Science with a concentration on Cloud Computing from Northeastern University, 
      along with hands-on experience on the Salesforce platform acquired through my work at PwC. 
      I have a knack for simplifying complex challenges into practical strategies using cloud technology, with a goal to drive innovation and create a lasting impact in the tech industry.
    skills:
      enable: true
      title: "My expertise spans across critical professional skills such as:"
      items:
        - "AWS"
        - "Kubernetes"
        - "Docker"
        - "JavaScript"
        - "Java"
        - "Python3"
        - "Apex"
        - "MySQL" 
        - "MongoDB"
        - "Salesforce SOQL" 
        - "Visualforce"
        - "Lightning Components"
        - "Salesforce API"
        - "GitHub"
        - "Jenkins"
        - "CI/CD"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Associate (Salesforce)"
        company: "PricewaterhouseCoopers (PwC)"
        date: "September 2021 - September 2022"
        content: |-
          - Developed responsive user interfaces with Visualforce pages and Aura Components, utilizing jQuery and Bootstrap for enhanced interactivity resulting in a 25% increase in user engagement.
          - Designed and deployed Lightning Web Components (LWC) for data display and user actions, including API callouts. Converted legacy Aura Components to LWC for better performance and reduced API response times by 20%.
          - Analyzed the XHR requests and eliminated redundant apex calls to improve performance which led to an overall improvement in page performance by 5.4 seconds.
          - Optimized Salesforce Health Cloud by configuring Patient Timeline and Patient Card, achieved a significant 30% decrease in user error rates, and improved user experience and accessibility.
          - Orchestrated the integration of over 12 APIs using REST and MuleSoft, ensuring robust data exchange and system integration.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Masters in Information Systems"
        school:
          name: "Northeastern University, Boston"
        date: "2022 - 2024"
        content: "Concentration: Cloud Computing"
        GPA: "3.68 out of 4.0"
        content: |-
          Relevant Coursework:
            - Advanced Cloud Computing Management, Network Security and Cloud Security, Web Design and Development, AWS Cloud Architecting, Enterprise Data Storage and Management, Cloud Analytics
      - title: "Bachelors of Technology in Computer Science and Engineering"
        school:
          name: "Jawaharlal Nehru Technological University"
        date: "2017 - 2021"
        content: |-
          Relevant Coursework:
            - Cloud Computing, Web Design and Development, DBMS, JavaScript, Python Programming, Problem Solving and Data Structures through C, Data Structures through C++, Object Oriented Programming through Java

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: AI-Enhanced Supplier Diversity GenAI Chatbot 
        content: "I led the development of a user-focused, AI-powered chatbot's front-end, enhancing engagement through research-driven design and seamless API integration for responsive and intuitive interactions in the higher education procurement space."
        image: /images/projects/genaichatbot.png
        featured:
          name: View Project
          link: https://github.com/AnanyaKakani/ 
        badges:
          - "Experiential Learning Capstone Project"
          - "JavScript"
          - "OpenAI"
          - "Pinecone Database"
          - "Python3"

      - title: Modernizing KnowQuest's Infrastructure 
        content: "Enhanced KnowQuest's web infrastructure using AWS, Kubernetes, and EC2, boosting scalability and securing systems. Automated the CI/CD pipeline with YAML, optimizing the development lifecycle and deployment efficiency. Strengthened security and monitoring by implementing CloudWatch and RBAC. Optimized network performance with Kubernetes, CoreDNS, and Ingress Controller, achieving unparalleled system efficiency."
        image: /images/projects/knowquest.jpeg
        featured:
          name: View Project
          link: https://github.com/AnanyaKakani/Modernizing-KnowQuest-Infrastructure
        badges:
          - "AWS"
          - "Kubernetes"
          - "CI/CD Strategies"

      - title: "Cybersecurity Strategy for Blue Bottle Coffee"
        content: "The cybersecurity strategy for Blue Bottle Coffee is structured around a strategic framework aligned with the National Institute of Standards and Technology (NIST) guidelines. 
                  It emphasizes strengthening the organization's defenses against cyber threats and ensuring the protection of sensitive data through the integration of advanced AWS security services.
"
        image: /images/projects/cybersecurity.png
        featured:
          name: View Project
          link: https://github.com/AnanyaKakani/Cybersecurity-Strategy-for-Blue-Bottle-Coffee
        badges:
          - "EC2"
          - "AWS CloudFront"
          - "AWS KMS"
          - "AWS GuardDuty"

      - title: Serverless Image Analysis and Management System 
        content: "Implemented a serverless architecture for automated image analysis with AWS services like S3, SQS, Lambda, and Rekognition, markedly improving efficiency and accuracy. Developed an event-driven workflow for processing image uploads and analyzing content with AWS Rekognition, coupled with result communication through SNS, showcasing cloud solutions expertise. Crafted and deployed an AWS S3 lifecycle policy to optimize image storage and retention, achieving compliance and cost efficiency via automated data management."
        image: /images/projects/amazonserverless.jpeg
        featured:
          name: View Project
          link: https://github.com/AnanyaKakani/Serverless-Image-Analysis-and-Management-System
        badges:
          - "AWS"
          - "S3"
          - "SQS"
          - "PAWS Rekognition"

      - title: "AWS Infrastructure for Healthcare Application"
        content: "Developed a secure, compliant AWS infrastructure for a healthcare SaaS application, focusing on scalability and data protection.
                  Implemented AWS EC2, S3, and RDS to support efficient data handling and global availability.
"
        image: /images/projects/aws healthcare project.jpeg
        featured:
          name: View Project
          link: https://github.com/AnanyaKakani/AWS-Infrastructure-for-Healthcare-Application
        badges:
          - "Python"
          - "Firebase"
          - "MySQL"
          - "Flask"

      - title: Interactive COVID-19 Awareness Website 
        content: "Developed a dynamic COVID-19 awareness website using HTML, CSS, and JavaScript, integrating WHO open-source APIs for real-time data visualization. Added user-centric features including login, registration, and an intuitive information display, enhancing user engagement and accessibility."
        image: /images/projects/corona.jpeg
        featured:
          name: View Project
          link: https://github.com/AnanyaKakani/UpdatesOfCovid19
        badges:
          - "Java"
          - "DBMS"
          - "TServlets"
          - "Hibernate"
          - "HTML"
          - "CSS"

      # - title: "Secure and Efficient Skyline Queries on Encrypted Data"
      #   content: "Developed a secure healthcare system using Flask, featuring encrypted file uploads and strict data privacy protocols. Introduced JWT for user authentication, registration, and session management among healthcare providers and users. Utilized Fernet encryption to safeguard patient data confidentiality, emphasizing data security. Showcased proficiency in web development, cloud architecture, and advanced security measures."
      #   image: /images/projects/skyline.png
      #   featured:
      #     name: View Project
      #     link: https://github.com/AnanyaKakani/skyline-project
      #   badges:
      #     - "Python"
      #     - "Firebase"
      #     - "MySQL"
      #     - "Flask"





  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: kakani.a.ui@gmail.edu
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/AnanyaKakani
      linkedin: https://www.linkedin.com/in/ananya-kakani-0671a71b5/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
